language: go
go:
  - "1.13.x"
  - tip

matrix:
  allow_failures:
    - go: tip
fast_finish: true

cache:
  directories:
    - $GOPATH/pkg/mod

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
