// Code generated by "stringer -type=TreeState"; DO NOT EDIT.

package gitstatus

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Default-0]
	_ = x[Rebasing-1]
	_ = x[AM-2]
	_ = x[AMRebase-3]
	_ = x[Merging-4]
	_ = x[CherryPicking-5]
	_ = x[Reverting-6]
	_ = x[Bisecting-7]
}

const _TreeState_name = "DefaultRebasingAMAMRebaseMergingCherryPickingRevertingBisecting"

var _TreeState_index = [...]uint8{0, 7, 15, 17, 25, 32, 45, 54, 63}

func (i TreeState) String() string {
	if i < 0 || i >= TreeState(len(_TreeState_index)-1) {
		return "TreeState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TreeState_name[_TreeState_index[i]:_TreeState_index[i+1]]
}
