on: [push, pull_request]
name: Coverage
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
      - run: go test -coverprofile=coverage.txt && bash <(curl -s https://codecov.io/bash)
